### ISSUE TITLE
Add common path in config 

### ISSUE THREAD

**Issue by evalsocket** [chronotc/monorepo-diff-buildkite-plugin#100]
Let's say we have a few common paths like gen files, lib/package, and other dependencies. In the current setup, we need to add them to all the services but if we have a common config then we just need to add it at one place 

example
```
steps:
  - label: "Triggering pipelines"
    plugins:
      - chronotc/monorepo-diff#v2.3.0:
          diff: "git diff --name-only $(head -n 1 last_successful_build)"
          interpolation: false
          env:
            - env1=env-1 # this will be appended to all env configuration
          hooks:
            - command: "echo $(git rev-parse HEAD) > last_successful_build"
          common:
                - "gen/"
                - "api/"
          watch:
            - path:
                - "ops/terraform/"
                - "ops/templates/terraform/"
              config:
                command: "buildkite-agent pipeline upload ops/.buildkite/pipeline.yml"
                label: "Upload pipeline"
                retry:
                  automatic:
                  - limit: 2
                    exit_status: -1
                agents:
                  queue: performance
                artifacts:
                  - "logs/*"
                env:
                  - FOO=bar
            - path: 
                - "foo-service/"
              config:
                trigger: "deploy-foo-service"
                label: "Triggered deploy"
                build:
                  message: "Deploying foo service"
                  env:
                    - HELLO=123
                    - AWS_REGION
          wait: true
```
