### ISSUE TITLE
`command` key is silently ignored if it contains a list of strings, rather than a single string

### ISSUE THREAD

**Issue by glittershark** [chronotc/monorepo-diff-buildkite-plugin#103]
eg, the following pipeline:

```yaml
steps:
  - plugins:
      - chronotc/monorepo-diff#v2.3.0:
          watch:
            - path: dir/
              config:
                label: step
                command:
                  - echo one
                  - echo two

```

generates the following pipeline on changes to the `dir/` directory:
```yaml
steps:
  - label: step
```

which then silently fails to upload (due to #101)
