### ISSUE TITLE
How to use `hooks` with a specific agent selection rule

### ISSUE THREAD

**Issue by armanm** [chronotc/monorepo-diff-buildkite-plugin#14]
I'm using this configuration

```yml
---
steps:
  - label: "Triggering pipelines :rocket:"
    plugins:
      - chronotc/monorepo-diff#v1.0.0:
          diff: "./script/modified-files.sh"
          watch:
            - path: "packages/api"
              config:
                trigger: "api"
            - path: "packages/infra"
              config:
                trigger: "infra"
          wait: true
          hooks:
            - command: echo "every that had to build is complete"
    agents:
      queue: custom-agents
```

This config specifies a `wait` and a `hooks` option. 

I'm seeing two things which are not what I expect:

1. `hooks` command is started in a separate build step as soon as the diff is complete. That means the `wait` command is being ignored.
2. the build steps for the `hooks` commands ignore the specified agent queue and instead set the queue to `default` which means no agent will pick the step up:

![image](https://user-images.githubusercontent.com/1578748/57423817-dd7a9e80-7258-11e9-81c1-1b0ec5c7dc22.png)

Am I missing something or is there a way to handle the above two points?

Thanks 🙂

**Comment by armanm** [comment]
I figure this this the way to do it:

```yml
---
steps:
  - label: "Triggering pipelines :rocket:"
    plugins:
      - chronotc/monorepo-diff#v1.0.0:
          diff: "./script/modified-files.sh"
          watch:
            - path: "packages/api"
              config:
                trigger: "api"
            - path: "packages/infra"
              config:
                trigger: "infra"
    agents:
      queue: custom-agents

  - wait: true

  - label: "Finally do this"
    command: "echo "every that had to build is complete"
    agents:
      queue: custom-agents
```
