### ISSUE TITLE
Use wildcard in path

### ISSUE THREAD

**Issue by guidodobboletta** [chronotc/monorepo-diff-buildkite-plugin#26]
I'd like to be able to set a "default" pipeline to be run if no other watch paths conditions are met. 

Example of how the configuration would look like:

```
      - chronotc/monorepo-diff#v1.1.1:
          watch:
            - path: "packer/"
              config:
                trigger: "packer"
            - path:
                - "*"
              config:
                trigger: "terraform"
          wait: true
```
