### ISSUE TITLE
Support Multiple Triggers

### ISSUE THREAD

**Issue by bradleyess** [chronotc/monorepo-diff-buildkite-plugin#28]
It's common for a monorepo to have many internal dependencies and whenever a change is detected in the dependency, it can be desirable to run the build of it's dependents as well to ensure no breaking changes have been introduced. Obviously this can be circumvented with contract testing, but we aren't there just yet.

Adding list support to the `trigger` configuration would enable this functionality.

```yml
            - path:
                - << *common_watch_paths
                - 'services/newsletter'
                - '.buildkite/pipelines/newsletter'
              config:
                trigger: 
                    - 'newsletter'
                    - 'website'
                build: { message: '${BUILDKITE_MESSAGE}', commit: '${BUILDKITE_COMMIT}', branch: '${BUILDKITE_BRANCH}' }
```
