### ISSUE TITLE
Support setting agent queue when running commands?

### ISSUE THREAD

**Issue by evandam** [chronotc/monorepo-diff-buildkite-plugin#32]
Would it be possible to add a way to specify an agent queue for the steps run by this plugin?

Ex:
```yaml
steps:
  - label: ":github:"
    plugins:
      - chronotc/monorepo-diff#v1.2.0:
          watch:
            - path: "dir1/"
              config:
                command: "echo hello"
                agent:
                  queues: ops
```
