### ISSUE TITLE
commit messages can trigger interpolation errors

### ISSUE THREAD

**Issue by pmenglund** [chronotc/monorepo-diff-buildkite-plugin#34]
If the commit message contains something like:

    A test change
    
    Testcase: how to break
    ```
    $ command line example
    ```

This will fail to run, as `buildkite pipeline upload` tries to interpolate the pipeline config the `monorepo-diff` generates.

The quick fix is to just add `--no-interpolation` to https://github.com/chronotc/monorepo-diff-buildkite-plugin/blob/408ce9c633eb532dad3a914c3c8336025b82f942/hooks/command#L29 but I don't know if someone depends on it being interpolated, so a better solution would be to add

```
    plugins:
      - chronotc/monorepo-diff#v1.3.0:
          no_interpolation: true
          watch:
            ...
```

so it is optional.
