### ISSUE TITLE
Is there a way to invoke pipelines/command one by one when multiple changes happened in multiple path?

### ISSUE THREAD

**Issue by JoeyDon** [chronotc/monorepo-diff-buildkite-plugin#39]
```
steps:
  - label: "Detecting which mono-repo has changed"
    plugins:
      - chronotc/monorepo-diff#v1.3.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "folder-a/"
              config:
                label: ":pipeline: Continue blue-alice pipeline"
                command: "buildkite-agent pipeline upload ./folder-a/.buildkite/pipeline.yml"
            - path: "folder-b/"
              config:
                label: ":pipeline: Continue dwh-store pipeline"
                command: "buildkite-agent pipeline upload ./folder-b/.buildkite/pipeline.yml"
```

Hey guys, my root directory's pipeline.yml looks like that. I have sub-directories having it's own defined `pipeline.yml`and all invoked from this root directory's pipeline.yml.

Is there a way that I can ensure each pipeline run in order? Currently I tried concurrency group and `- wait` in each sub-directoriy's `pipeline.yml` but no luck.

Would really appreciate your thinking and replies!
