### ISSUE TITLE
add support for artifacts

### ISSUE THREAD

**Issue by worxli** [chronotc/monorepo-diff-buildkite-plugin#40]
It should be possible to collect artifacts from a command triggered by the monorepo diff plugin:

```
plugins:
  - chronotc/monorepo-diff#v1.3.0:
      watch:
      - path:
        - tests/X
        config:
          command: "run test X"
          artifact_paths:
          - logs/tests/*
```
