### ISSUE TITLE
Add support for globs in paths

### ISSUE THREAD

**Issue by worxli** [chronotc/monorepo-diff-buildkite-plugin#61]
It would be useful to trigger certain pipeline only for specific file types. E.g. the markdown linting command/pipeline only for changes in files that end in `.md`. For this it would be useful to have glob support in paths.

Proposal:
```
steps:
  - label: "Triggering pipelines"
    plugins:
      - chronotc/monorepo-diff#v2.0.3:
          watch:
            - path: "**/*.md"
              config:
                command: "lint markdown"
```
