### ISSUE TITLE
Question/Feature Request: Get current path?

### ISSUE THREAD

**Issue by phazel** [chronotc/monorepo-diff-buildkite-plugin#72]
Hi there. This is a question and potentially feature request if it's not currently possible and other people are interested. I see that the contribution guidelines ask that we start a discussion first, however I can't see the Discussions tab so apologies for writing in the wrong place.

What I'd like to do is, inside a child pipeline, refer to the name of the path used to trigger that pipeline. This would allow the child pipeline to be aware of which directory in the monorepo it belongs to. Here is my usecase:

```sh
# Repo Structure

.buildkite/
    pipeline.yml
    build.sh
    lint.sh
    test.sh
project-a/
    .buildkite/
        pipeline.yml
project-b/
    .buildkite/
        pipeline.yml
```
```yml
# .buildkite/pipeline.yml

steps:
  - label: ":arrow_right:"
    plugins:
      - chronotc/monorepo-diff#v2.0.4:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "project-a/"
              config:
                trigger: project-a
            - path: "project-b/"
              config:
                trigger: project-b
```
```yml
# project-a/.buildkite/pipeline.yml

steps:
  -  command: "./.buildkite/lint.sh project-a"
  -  command: "./.buildkite/build.sh project-a"
```
```yml
# project-b/.buildkite/pipeline.yml

steps:
  -  command: "./.buildkite/lint.sh project-b"
  -  command: "./.buildkite/test.sh project-b"
```

Inside each `.sh` file, I am `cd`ing into the directory, in this case `project-a` or `project-b` in order to run the given task for that step. This is passed as a parameter as in `command: "./.buildkite/lint.sh project-a"`. eg. the `lint.sh` file contains:
```sh
# .buildkite/lint.sh

...
cd $1
npm i
npm run lint
cd -
```

Instead of passing the directory as a parameter to the scripts, I'd like to be able to handle this programmatically. An environment variable would do fine and would fit the [Buildkite pattern](https://buildkite.com/docs/pipelines/environment-variables) for accessing meta-level information but anything would do really.

This could be accessible within the script, eg.
```sh
# .buildkite/lint.sh

...
cd $MONOREPO_DIFF_PATH
npm i
npm run lint
cd -
```
Or kept as a script parameter but accessible from the child pipeline config, eg.
```yml
# project-a/.buildkite/pipeline.yml

command: "./.buildkite/lint.sh $MONOREPO_DIFF_PATH"
```

### Use current directory

This doesn't work because the child pipelines are still being run at the top level of the repo so `pwd` won't help, and `$0` doesn't help because the scripts live in the parent `.buildkite` directory.

### Use pipeline slug

I happen to be using a pattern where the project directories are a match with the pipeline slugs, however this is really more for clarity than utility. I'm very reluctant to start coupling pipeline slugs directly with directory names for maintainability purposes.

Of the options available, I consider my least worst option to be hardcoding the directory names in each child `pipeline.yml` file and passing them into the scripts, as I'm already doing. It's very prone to human error, and I've already found myself making copy-pasting mistakes just with two child pipelines which cause me to run the wrong thing. That kind of error might go unnoticed for a long time, so I'd like to avoid it entirely. Is there a better way I'm not seeing, or could it be possible to add a feature to the plugin which allows me to interrogate the context in this way? Thanks for reading.
