### ISSUE TITLE
Group Merging Support

### ISSUE THREAD

**Issue by BoraxTheClean** [chronotc/monorepo-diff-buildkite-plugin#82]
I'd like to use [group merging](https://buildkite.com/docs/pipelines/group-step#group-merging) to merge the monorepo step that triggers my steps into one buildkite tile in the UI.

Thus I'd like to be able to add a group in my `config`

```
            - path:
                - "**/*.js"
              config:
                group: prettier
                label: ":sparkles: :nail_care: Prettier"
                command: "buildkite-agent pipeline upload ./.buildkite/prettier.yml"
```

So that it would merge with my uploaded pipeline:

```
steps:
  - group: prettier
    steps:
      - label: ":sparkles: :nail_care: Prettier"
        command:
          - prettier
```

An alternative, and perhaps more correct config structure would be:
```
            - path:
                - "**/*.js"
              config:
                group: prettier
                steps:
                  - label: ":sparkles: :nail_care: Prettier"
                    command: "buildkite-agent pipeline upload ./.buildkite/prettier.yml"
```
